In [1]:
import numpy as np

In [ ]:
#-1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення
v = np.arange(1, 11)
print(v)

In [ ]:
#-2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
matr = np.zeros((3, 3))
print(matr)

In [ ]:
#-3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
matr = np.random.randint(1, 11, size=(5, 5))
print(matr)

In [ ]:
#-4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matr = np.random.rand(4, 4)
print(matr)

In [ ]:
#-5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)
print("array1 ->",array1)
print("array2 ->", array2)
print("\n")
add = array1 + array2
subtract = array1 - array2
multiplication = array1 * array2
print("+", add)
print("-", subtract)
print("*", multiplication)

In [ ]:
#-6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
v1 = np.array([10, 5, 66, 1, 22, 4, 8])
v2 = np.array([5, 9, 77, 36, 88, 1, 99])

scalar_res = np.dot(v1, v2)
print(scalar_res)

In [ ]:
#-7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
matr1 = np.random.randint(1, 11, (2, 2))
matr2 = np.random.randint(1, 11, (2, 3))
print(matr1, "\n")
print(matr2)
print("\n")
res = np.dot(matr1, matr2)
print(res)

In [ ]:
#-8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matr = np.random.randint(1, 11, (3, 3))
print(matr)
print("\n")
inverse_matr = np.linalg.inv(matr)
print(inverse_matr)

In [ ]:
#-9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matr = np.random.rand(4, 4)
print(matr)
print("\n")
transp_matr = np.transpose(matr)
print(transp_matr)

In [ ]:
#-10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matr = np.random.randint(1, 11, (3, 4))
v = np.random.randint(1, 11, 4)
print(matr, "\n")
print(v)
print("\n")

res = np.dot(matr, v)
print(res)

In [ ]:
#-11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matr = np.random.rand(2, 3)
v = np.random.rand(3)
print(matr, "\n")
print(v)
print("\n")

res = np.dot(matr, v)
print(res)

In [ ]:
#-12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matr1 = np.random.randint(1, 11, (2, 2))
matr2 = np.random.randint(1, 11, (2, 2))
print(matr1, "\n")
print(matr2)
print("\n")

res = np.multiply(matr1, matr2)
print(res)

In [ ]:
#-13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matr1 = np.random.randint(1, 11, (2, 2))
matr2 = np.random.randint(1, 11, (2, 2))
print(matr1, "\n")
print(matr2)
print("\n")

res = np.dot(matr1, matr2)
print(res)

In [32]:
#-14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matr = np.random.randint(1, 101, (5, 5))
print(matr1, "\n")

sum_el = np.sum(matr)
print(sum_el)

[[3 9]
 [2 3]] 

1087


In [ ]:
#-15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matr1 = np.random.randint(1, 11, (4, 4))
matr2 = np.random.randint(1, 11, (4, 4))
print(matr1, "\n")
print(matr2)
print("\n")

res  = matr1 - matr2
print(res)


In [ ]:
#-16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matr = np.random.rand(3, 3)
print(matr1, "\n")

row_sum = np.sum(matr, axis=1)
print(row_sum, "\n")

res = row_sum.reshape(-1, 1)
print(res)


In [ ]:
#-17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matr = np.random.randint(1, 11, (3, 4))
print(matr, "\n")

res = np.square(matr)
print(res)

In [45]:
#-18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
v = np.random.randint(1, 51, 4)
print(v, "\n")

res = np.sqrt(v)
print(res)

[ 2 17 16 17] 

[1.41421356 4.12310563 4.         4.12310563]
