In [2]:
import numpy as np

In [3]:
#-1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення
v = np.arange(1, 11)
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#-2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
matr = np.zeros((3, 3))
print(matr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#-3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
matr = np.random.randint(1, 11, size=(5, 5))
print(matr)

[[ 7  9  8  9  2]
 [ 7 10  4  9  6]
 [ 9  3  2  5  9]
 [ 1  1  6  3  9]
 [ 3 10  9  5  4]]


In [6]:
#-4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matr = np.random.rand(4, 4)
print(matr)

[[0.2166024  0.78830404 0.82877311 0.95216758]
 [0.65105674 0.9999225  0.01303572 0.964594  ]
 [0.58213717 0.46911895 0.91356816 0.63430164]
 [0.99427078 0.14399004 0.64860432 0.38063423]]


In [7]:
#-5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)
print("array1 ->",array1)
print("array2 ->", array2)
print("\n")
add = array1 + array2
subtract = array1 - array2
multiplication = array1 * array2
print("+", add)
print("-", subtract)
print("*", multiplication)

array1 -> [ 2 10  4  2  3]
array2 -> [ 8 10  5  6  2]


+ [10 20  9  8  5]
- [-6  0 -1 -4  1]
* [ 16 100  20  12   6]


In [8]:
#-6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
v1 = np.array([10, 5, 66, 1, 22, 4, 8])
v2 = np.array([5, 9, 77, 36, 88, 1, 99])

scalar_res = np.dot(v1, v2)
print(scalar_res)

7945


In [9]:
#-7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
matr1 = np.random.randint(1, 11, (2, 2))
matr2 = np.random.randint(1, 11, (2, 3))
print(matr1, "\n")
print(matr2)
print("\n")
res = np.dot(matr1, matr2)
print(res)

[[3 2]
 [3 2]] 

[[3 4 3]
 [4 2 8]]


[[17 16 25]
 [17 16 25]]


In [10]:
#-8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matr = np.random.randint(1, 11, (3, 3))
print(matr)
print("\n")
inverse_matr = np.linalg.inv(matr)
print(inverse_matr)

[[6 2 4]
 [4 7 7]
 [2 9 8]]


[[-0.7  2.  -1.4]
 [-1.8  4.  -2.6]
 [ 2.2 -5.   3.4]]


In [11]:
#-9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matr = np.random.rand(4, 4)
print(matr)
print("\n")
transp_matr = np.transpose(matr)
print(transp_matr)

[[0.75785959 0.14709418 0.7603626  0.90817001]
 [0.58081978 0.82390687 0.97429041 0.43771337]
 [0.67527678 0.88917663 0.55630818 0.86148009]
 [0.56710179 0.21609211 0.4171397  0.72563802]]


[[0.75785959 0.58081978 0.67527678 0.56710179]
 [0.14709418 0.82390687 0.88917663 0.21609211]
 [0.7603626  0.97429041 0.55630818 0.4171397 ]
 [0.90817001 0.43771337 0.86148009 0.72563802]]


In [12]:
#-10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matr = np.random.randint(1, 11, (3, 4))
v = np.random.randint(1, 11, 4)
print(matr, "\n")
print(v)
print("\n")

res = np.dot(matr, v)
print(res)

[[8 9 3 5]
 [3 4 2 4]
 [5 6 2 1]] 

[3 5 2 1]


[80 37 50]


In [13]:
#-11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matr = np.random.rand(2, 3)
v = np.random.rand(3)
print(matr, "\n")
print(v)
print("\n")

res = np.dot(matr, v)
print(res)

[[0.05156728 0.86193913 0.98841619]
 [0.00165732 0.09929598 0.59323707]] 

[0.8059456  0.21088835 0.63212146]


[0.84813243 0.39727396]


In [14]:
#-12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matr1 = np.random.randint(1, 11, (2, 2))
matr2 = np.random.randint(1, 11, (2, 2))
print(matr1, "\n")
print(matr2)
print("\n")

res = np.multiply(matr1, matr2)
print(res)

[[6 9]
 [2 5]] 

[[1 9]
 [8 5]]


[[ 6 81]
 [16 25]]


In [15]:
#-13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matr1 = np.random.randint(1, 11, (2, 2))
matr2 = np.random.randint(1, 11, (2, 2))
print(matr1, "\n")
print(matr2)
print("\n")

res = np.dot(matr1, matr2)
print(res)

[[ 2  6]
 [10 10]] 

[[5 4]
 [4 9]]


[[ 34  62]
 [ 90 130]]


In [16]:
#-14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matr = np.random.randint(1, 101, (5, 5))
print(matr1, "\n")

sum_el = np.sum(matr)
print(sum_el)

[[ 2  6]
 [10 10]] 

1364


In [17]:
#-15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matr1 = np.random.randint(1, 11, (4, 4))
matr2 = np.random.randint(1, 11, (4, 4))
print(matr1, "\n")
print(matr2)
print("\n")

res  = matr1 - matr2
print(res)


[[ 2  7  5  6]
 [ 7  4  2  6]
 [10  6  3  2]
 [ 3  1  8  5]] 

[[1 2 8 4]
 [7 2 5 1]
 [7 6 5 6]
 [2 4 8 4]]


[[ 1  5 -3  2]
 [ 0  2 -3  5]
 [ 3  0 -2 -4]
 [ 1 -3  0  1]]


In [18]:
#-16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matr = np.random.rand(3, 3)
print(matr1, "\n")

row_sum = np.sum(matr, axis=1)
print(row_sum, "\n")

res = row_sum.reshape(-1, 1)
print(res)


[[ 2  7  5  6]
 [ 7  4  2  6]
 [10  6  3  2]
 [ 3  1  8  5]] 

[1.59265443 0.79991607 1.73620604] 

[[1.59265443]
 [0.79991607]
 [1.73620604]]


In [19]:
#-17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matr = np.random.randint(1, 11, (3, 4))
print(matr, "\n")

res = np.square(matr)
print(res)

[[6 4 9 3]
 [2 2 1 2]
 [2 7 2 5]] 

[[36 16 81  9]
 [ 4  4  1  4]
 [ 4 49  4 25]]


In [20]:
#-18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
v = np.random.randint(1, 51, 4)
print(v, "\n")

res = np.sqrt(v)
print(res)

[41  9 40 27] 

[6.40312424 3.         6.32455532 5.19615242]
