In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import random

In [26]:
#Функція гіпотези лінійної регресії у векторному вигляді
def mean_squared_error(y_true, y_pred):
  mse = np.mean((y_true - y_pred) ** 2)
  return mse

In [3]:
#Функція для обчислення функції втрат у векторному вигляді
def cross_entropy_loss(y_true, y_pred):
  y_pred = np.clip(y_pred)
  ce_loss = np.sum(y_true * np.log(y_pred))
  return ce_loss

In [4]:
#Один крок градієнтного спуску
def one_step_gradient(X, y, weights, lr = 0.001):
    m = len(y)
    predictions = np.dot(X, weights)
    errors = predictions - y
    gradient = (1/m) * np.dot(X.T, errors)
    w = weights - lr * gradient
    return w

In [5]:
url = "https://drive.google.com/uc?id=1-rAa4XT4_fI0dOBlMNuE6a7jB0wln_Qo"

In [6]:
data_fr = pd.read_csv(url)
data_fr

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [7]:
data_fr2 = data_fr[["area", "bedrooms", "bathrooms"]]
target = data_fr['price']
data_fr2.head()

area  bedrooms  bathrooms
0  7420         4          2
1  8960         4          4
2  9960         3          2
3  7500         4          2
4  7420         4          1

In [8]:
m = np.array(data_fr2)
m

array([[7420,    4,    2],
       [8960,    4,    4],
       [9960,    3,    2],
       ...,
       [3620,    2,    1],
       [2910,    3,    1],
       [3850,    3,    1]])

In [9]:
matr_X = data_fr2.values
print(len(matr_X))

545


In [10]:
matr_y = np.array(target)
print(len(matr_y))

545


In [38]:
#weights = weights - lr * np.dot(x.transpose(), (y_pred - y)) / m
w = np.array([random. uniform(-5, 5) for i in range(matr_X.shape[1] + 1)])
w

array([-0.80521797,  0.60364165, -0.75838002, -3.23426805])

In [39]:
matr = np.ones((len(matr_X), 1))
X = np.concatenate((matr, matr_X), axis=1)
result = one_step_gradient(X, matr_y, w)
result

array([4.76282216e+03, 2.67041076e+07, 1.46289247e+04, 6.60931724e+03])

In [40]:
model = LinearRegression()
regress = model.fit(matr_X, matr_y)
print(regress.coef_)
print(regress.intercept_)
y_test = model.predict(matr_X)
print(y_test)
print(f"Середньо квадратична помилка - {mean_squared_error(matr_y, y_test)}")
print(regress.predict(np.array([[7500, 4, 2]])))

[3.78762754e+02 4.06820034e+05 1.38604950e+06]
-173171.6076326361
[ 7036627.15462756 10392020.79073062  7591864.51496455  7066928.17491437
  5650577.65683656  8046157.63893619  8862041.44657728 12155033.66266496
  5908136.32927443  5997273.32237126  7433006.33878929  7884833.54232771
  6707103.55900852  5551877.16057395  6773736.96722072  5112734.54674571
  6726041.69668778  7038870.89473029  5561696.15574839  6251044.36727328
  4069593.08695356  6529434.99115833  5482378.157826    5546545.64560498
  7152499.72080582  6703315.93147267  6091964.01076753  5794857.42953371
  7644191.44779685  6309402.66774416  6650639.07230556  5084677.26656164
  6074569.7605214   7462862.99841513  5837715.29352638  6470726.76435264
  6653290.41158066  7635072.30529203  4705914.51297653  6498784.04453671
  4914234.02744834  6228318.60205817  6273770.13248838  6498784.04453671
  6498784.04453671  6091964.01076753  6091964.01076753  4933172.1651276
  5448067.32967285  6637382.37593008  6637382.37593008  482

In [ ]:
#Аналітичне рішення
matr = np.ones((len(matr_X), 1))

In [19]:
#X = np.concatenate((add_matr, matr_X[109:]), axis=1)
X = np.concatenate([np.ones((len(matr_X), 1)), matr_X], axis=1)
print(X)

[[1.00e+00 7.42e+03 4.00e+00 2.00e+00]
 [1.00e+00 8.96e+03 4.00e+00 4.00e+00]
 [1.00e+00 9.96e+03 3.00e+00 2.00e+00]
 ...
 [1.00e+00 3.62e+03 2.00e+00 1.00e+00]
 [1.00e+00 2.91e+03 3.00e+00 1.00e+00]
 [1.00e+00 3.85e+03 3.00e+00 1.00e+00]]


In [36]:
w = np.linalg.inv(X.T @ X) @ X.T @ matr_y
w

array([-1.73171608e+05,  3.78762754e+02,  4.06820034e+05,  1.38604950e+06])

In [29]:
predict = np.dot(w, X.T)
y_pred = model.predict(matr_X)
result2 = mean_squared_error(predict, matr_y)
print (predict)
print (result2)

[ 7036627.15462757 10392020.79073062  7591864.51496455  7066928.17491437
  5650577.65683657  8046157.63893619  8862041.44657728 12155033.66266496
  5908136.32927444  5997273.32237126  7433006.33878929  7884833.54232772
  6707103.55900852  5551877.16057396  6773736.96722072  5112734.54674572
  6726041.69668778  7038870.8947303   5561696.15574839  6251044.36727328
  4069593.08695356  6529434.99115833  5482378.157826    5546545.64560498
  7152499.72080583  6703315.93147267  6091964.01076753  5794857.42953371
  7644191.44779685  6309402.66774416  6650639.07230556  5084677.26656164
  6074569.7605214   7462862.99841513  5837715.29352639  6470726.76435264
  6653290.41158066  7635072.30529203  4705914.51297654  6498784.04453672
  4914234.02744834  6228318.60205817  6273770.13248838  6498784.04453672
  6498784.04453672  6091964.01076753  6091964.01076753  4933172.1651276
  5448067.32967286  6637382.37593009  6637382.37593009  4829012.40789169
  6498784.04453672  5770015.6702202   6091964.010767

In [ ]:
# [-0.80521797,  0.60364165, -0.75838002, -3.23426805]
# [-1.73171608e+05,  3.78762754e+02,  4.06820034e+05,  1.38604950e+06]